<?php

namespace Database\Seeders;

use App\Models\Activity;
use Illuminate\Database\Seeder;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $activity = new Activity();
        $activity->name = "Libro";
        $activity->slug = "Libro";
        $activity->description = "Es una artefacto que para la cultura Náhuatl era muy sagrado y lo llamaban Amoch";
        $activity->question = "¿Cómo se dice libro en Náhuatl?";
        $activity->answer = "amoch";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Globo";
        $activity->slug = "Globo";
        $activity->description = "Es un objeto hecho de goma o material flexible que se llena de gas o aire y en la cultura Náhuatl lo llaman Apompo ";
        $activity->question = "¿Cómo se dice globo en Náhuatl?";
        $activity->answer = "apompo";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Melón";
        $activity->slug = "Melón";
        $activity->description = "Es una fruta diurética, estomacal, rehidratante y un excelente depurativo, en la cultura Náhuatl lo llaman Meloj";
        $activity->question = "¿Cómo se dice melón en Náhuatl?";
        $activity->answer = "meloj";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Limón";
        $activity->slug = "Limón";
        $activity->description = "Esta fruta es rica en agua y fibra, contiene altas concentraciones de ácido cítrico y vitamina C, en la cultura Náhuatl lo llaman Limo";
        $activity->question = "¿Cómo se dice limón en Náhuatl?";
        $activity->answer = "limo";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Sol";
        $activity->slug = "Sol";
        $activity->description = "Estrella con luz propia alrededor de la cual gira la Tierra, se le llama Tona en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice sol en Náhuatl?";
        $activity->answer = "tona";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Nube";
        $activity->slug = "Nube";
        $activity->description = "Masa de vapor formada por gotas de agua que se encuentra suspendida en la atmósfera, en la cultura Náhuatl se le conoce como Mixtli";
        $activity->question = "¿Cómo se dice nube en Náhuatl?";
        $activity->answer = "mixtli";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Padre";
        $activity->slug = "Padre";
        $activity->description = "Miembro familiar del sexo masculino que ha tenido descendencia directa, en la cultura Náhuatl se le conoce como Tata";
        $activity->question = "¿Cómo se dice padre en Náhuatl?";
        $activity->answer = "tata";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Mamá";
        $activity->slug = "Mamá";
        $activity->description = "Miembro familiar del sexo femenino que ha tenido descendencia directa, en la cultura Náhuatl se le conoce como Nana";
        $activity->question = "¿Cómo se dice mamá en Náhuatl?";
        $activity->answer = "nana";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Pan";
        $activity->slug = "Pan";
        $activity->description = "Alimento que consiste en una masa de harina, trigo, levadura y agua, cocida en un horno, en la cultura Náhuatl se le conoce como Pantsi";
        $activity->question = "¿Cómo se dice pan en Náhuatl?";
        $activity->answer = "pantsi";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Carne";
        $activity->slug = "Carne";
        $activity->description = "Parte del cuerpo de los animales preparada para el consumo humano, en la cultura Náhuatl se le llama Nakatl";
        $activity->question = "¿Cómo se dice carne en Náhuatl?";
        $activity->answer = "nakatl";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Perro";
        $activity->slug = "Perro";
        $activity->description = "Mamífero carnívoro doméstico que se caracteriza por su inteligencia y fidelidad al ser humano, en la cultura náhuatl se le conoce como Chichi";
        $activity->question = "¿Cómo se dice perro en Náhuatl?";
        $activity->answer = "chichi";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Mono";
        $activity->slug = "Mono";
        $activity->description = "Nombre genérico con que se designa a cualquiera de los primates, en la cultura Náhuatl se le conoce como Miko";
        $activity->question = "¿Cómo se dice mono en Náhuatl?";
        $activity->answer = "miko";
        $activity->course_id = 1;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Juguete";
        $activity->slug = "Juguete";
        $activity->description = "Es el artefacto con el que pasan horas de diversión los niños, en la cultura náhuatl se le conoce como Ajauili";
        $activity->question = "¿Cómo se dice juguete en Náhuatl?";
        $activity->answer = "ajauili";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Sandía";
        $activity->slug = "Sandía";
        $activity->description = "Fruta grande cuya pulpa es de color rojizo y de sabor dulce, aporta vitaminas y minerales, se le llama ualeya en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice sandía en Náhuatl?";
        $activity->answer = "ualeya";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Nopal";
        $activity->slug = "Nopal";
        $activity->description = "Planta originaria de México formada por una serie de paletas ovales con espinas, en la cultura Náhuatl se le conoce como nejpali";
        $activity->question = "¿Cómo se dice nopal en Náhuatl?";
        $activity->answer = "nejpali";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Palma";
        $activity->slug = "Palma";
        $activity->description = "Árbol que crece hasta 20 metros de altura con tronco áspero y cilíndrico, se le conoce como apachtli en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice palma en Náhuatl?";
        $activity->answer = "apachtli";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Estrella";
        $activity->slug = "Estrella";
        $activity->description = "Cada uno de los cuerpos celestes que brillan en la noche, excepto la Luna, en la cultura Náhuatl se le llama sitlalij";
        $activity->question = "¿Cómo se dice estrella en Náhuatl?";
        $activity->answer = "sitlalij";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Hermano";
        $activity->slug = "Hermano";
        $activity->description = "Ser humano de sexo masculino que tiene en común los mismos padres o uno de ellos, en la cultura Náhuatl se le conoce como mimi";
        $activity->question = "¿Cómo se dice hermano en Náhuatl?";
        $activity->answer = "mimi";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Hermana";
        $activity->slug = "Hermana";
        $activity->description = "Ser humano de sexo femenino que tiene en común los mismos padres o uno de ellos, en la cultura Náhuatl se le conoce como pipi";
        $activity->question = "¿Cómo se dice hermana en Náhuatl?";
        $activity->answer = "pipi";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Águila";
        $activity->slug = "Águila";
        $activity->description = "Ave de rapiña de gran tamaño considerada la reina de las aves, se le conoce como kuajtli en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice águila en Náhuatl?";
        $activity->answer = "kuajtli";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Búho";
        $activity->slug = "Búho";
        $activity->description = " Ave que persigue a otros animales para alimentarse y tiene hábitos nocturnos, en la cultura Náhuatl se le conoce como tekolotl";
        $activity->question = "¿Cómo se dice búho en Náhuatl?";
        $activity->answer = "tekolotl";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Rana";
        $activity->slug = "Rana";
        $activity->description = "Anfibio con piel arrugada y muchas pintas, se caracteriza por saltar de un lado a otro, en la cultura Náhuatl se le conoce como pechpechi";
        $activity->question = "¿Cómo se dice rana en Náhuatl?";
        $activity->answer = "pechpechi";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Cabeza";
        $activity->slug = "Cabeza";
        $activity->description = "Parte superior del cuerpo donde se encuentran algunos de los sentidos y el cerebro, se le conoce como tsonteko en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice cabeza en Náhuatl?";
        $activity->answer = "tsonteko";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Boca";
        $activity->slug = "Boca";
        $activity->description = "Situada en la parte inferior de la cara donde se reciben los alimentos, en la cultura Náhuatl se le conoce como kamaktli";
        $activity->question = "¿Cómo se dice boca en Náhuatl?";
        $activity->answer = "kamaktli";
        $activity->course_id = 2;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Almohada";
        $activity->slug = "Almohada";
        $activity->description = "Bolsa de tela suave y fina que sirve para apoyar la cabeza cuando se duerme, se le conoce como tsontetomitl en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice almohada en Náhuatl?";
        $activity->answer = "tsontetomitl";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Cuchara";
        $activity->slug = "Cuchara";
        $activity->description = "Utensilio que sirve especialmente para llevar a la boca cosas líquidas o blandas, en la cultura Náhuatl se le conoce como makomoli";
        $activity->question = "¿Cómo se dice cuchara en Náhuatl?";
        $activity->answer = "makomoli";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Piña";
        $activity->slug = "Piña";
        $activity->description = "Fruta de forma ovalada y gruesa de color amarilla cuya pulpa es comestible, se le conoce como matsajtli en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice piña en Náhuatl?";
        $activity->answer = "matsajtli";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Plátano";
        $activity->slug = "Plátano";
        $activity->description = "Fruta amarilla de forma alargada rica en fibra y potasio, en la cultura Náhuatl se le conoce como xochikuali";
        $activity->question = "¿Cómo se dice plátano en Náhuatl?";
        $activity->answer = "xochikuali";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Luna";
        $activity->slug = "Luna";
        $activity->description = "Único satélite natural de la Tierra, se le conoce como meetstli en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice luna en Náhuatl?";
        $activity->answer = "meetstli";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Mundo";
        $activity->slug = "Mundo";
        $activity->description = "Es el conjunto de todo lo existente, se le conoce como tlaltipaktli en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice mundo en Náhuatl?";
        $activity->answer = "tlaltipaktli";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Niño";
        $activity->slug = "Niño";
        $activity->description = "Persona que se encuentra en la etapa de la niñez, en la cultura Náhuatl se le conoce como okichpil";
        $activity->question = "¿Cómo se dice niño en Náhuatl?";
        $activity->answer = "okichpil";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Abuelo";
        $activity->slug = "Abuelo";
        $activity->description = "Nombre que se le da al padre y madre de sus padres, en la cultura Náhuatl se le conoce como koli";
        $activity->question = "¿Cómo se dice abuelo en Náhuatl?";
        $activity->answer = "koli";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Ardilla";
        $activity->slug = "Ardilla";
        $activity->description = "Mamífero roedor que se cría en bosques, es inquieto y ligero, se le conoce como tokomajtli en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice ardilla en Náhuatl?";
        $activity->answer = "tokomajtli";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Abeja";
        $activity->slug = "Abeja";
        $activity->description = "Insecto que se caracteriza principalmente por ser productor de miel, se le conoce como neksayoli en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice abeja en Náhuatl?";
        $activity->answer = "neksayoli";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Nariz";
        $activity->slug = "Nariz";
        $activity->description = "Prominente del rostro humano que forma parte del aparato respiratorio, en la cultura Náhuatl se le conoce como yakatsoli";
        $activity->question = "¿Cómo se dice nariz en Náhuatl?";
        $activity->answer = "yakatsoli";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Oreja";
        $activity->slug = "Oreja";
        $activity->description = "Parte del cuerpo cuya misión es percibir los sonidos a través de las vibraciones, se le conoce como nakastli en la cultura Náhuatl";
        $activity->question = "¿Cómo se dice oreja en Náhuatl?";
        $activity->answer = "nakastli";
        $activity->course_id = 3;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Escalera";
        $activity->slug = "Escalera-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice escalera en Maya?";
        $activity->answer = "eeb";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Trompeta";
        $activity->slug = "Trompeta-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice trompeta en Maya?";
        $activity->answer = "jom";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Aguacate";
        $activity->slug = "Aguacate-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice aguacate en Maya?";
        $activity->answer = "oon";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Chile";
        $activity->slug = "Chile-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice chile en Maya?";
        $activity->answer = "lik";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Luna";
        $activity->slug = "Luna-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice luna en Maya?";
        $activity->answer = "uj";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Estrella";
        $activity->slug = "Estrella-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice estrella en Maya?";
        $activity->answer = "eek'";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Padre";
        $activity->slug = "Padre-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice padre en Maya?";
        $activity->answer = "taata";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Madre";
        $activity->slug = "Madre-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice madre en Maya?";
        $activity->answer = "na'";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Pan";
        $activity->slug = "Pan-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice pan en Maya?";
        $activity->answer = "waaj";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Araña";
        $activity->slug = "Araña-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice araña en Maya?";
        $activity->answer = "am";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Pescado";
        $activity->slug = "Pescado-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice pescado en Maya?";
        $activity->answer = "kay";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Nariz";
        $activity->slug = "Nariz-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice nariz en Maya?";
        $activity->answer = "ni'";
        $activity->course_id = 4;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Tronco";
        $activity->slug = "Tronco-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice tronco en Maya?";
        $activity->answer = "chuun";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Casa";
        $activity->slug = "Casa-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice casa en Maya?";
        $activity->answer = "naaj";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Papaya";
        $activity->slug = "Papaya-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice papaya en Maya?";
        $activity->answer = "puut";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Cebolla";
        $activity->slug = "Cebolla-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice cebolla en Maya?";
        $activity->answer = "kukut";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Flor";
        $activity->slug = "Flor-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice flor en Maya?";
        $activity->answer = "lool";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Mundo";
        $activity->slug = "Mundo-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice mundo en Maya?";
        $activity->answer = "kaab";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Abuelo";
        $activity->slug = "Abuelo-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice abuelo en Maya?";
        $activity->answer = "nool";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Abuela";
        $activity->slug = "Abuela-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice abuela en Maya?";
        $activity->answer = "chiich";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Carne";
        $activity->slug = "Carne-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice carne en Maya?";
        $activity->answer = "bak'";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Ardilla";
        $activity->slug = "Ardilla-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice ardilla en Maya?";
        $activity->answer = "kunab";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Gato";
        $activity->slug = "Gato-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice gato en Maya?";
        $activity->answer = "miis";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Cabeza";
        $activity->slug = "Cabeza-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice cabeza en Maya?";
        $activity->answer = "pool";
        $activity->course_id = 5;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Libro";
        $activity->slug = "Libro-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice libro en Maya?";
        $activity->answer = "ánaltee'";
        $activity->course_id = 6;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Silla";
        $activity->slug = "Silla-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice silla en Maya?";
        $activity->answer = "kulxekil";
        $activity->course_id = 6;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Platano";
        $activity->slug = "Platano-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice plátano en Maya?";
        $activity->answer = "Ja'as";
        $activity->course_id = 6;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Guayaba";
        $activity->slug = "Guayaba-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice guayaba en Maya?";
        $activity->answer = "pichi'";
        $activity->course_id = 6;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Palma";
        $activity->slug = "Palma-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice palma en Maya?";
        $activity->answer = "xa'an";
        $activity->course_id = 6;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Nube";
        $activity->slug = "Nube-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice nube en Maya?";
        $activity->answer = "múuyal";
        $activity->course_id = 6;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Niño";
        $activity->slug = "Niño-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice niño en Maya?";
        $activity->answer = "paal";
        $activity->course_id = 6;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Hermana";
        $activity->slug = "Hermana-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice hermana en Maya?";
        $activity->answer = "kiik";
        $activity->course_id = 6;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Caballo";
        $activity->slug = "Caballo-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice caballo en Maya?";
        $activity->answer = "tsíimin";
        $activity->course_id = 6;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Borrego";
        $activity->slug = "Borrego-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice borrego en Maya?";
        $activity->answer = "taman";
        $activity->course_id = 6;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Hombro";
        $activity->slug = "Hombro-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice hombro en Maya?";
        $activity->answer = "keléembal";
        $activity->course_id = 6;
        $activity->save();
        $activity = new Activity();
        $activity->name = "Pierna";
        $activity->slug = "Pierna-MY";
        $activity->description = "";
        $activity->question = "¿Cómo se dice pierna en Maya?";
        $activity->answer = "muk'ook";
        $activity->course_id = 6;
        $activity->save();
    }
}
