<?php

namespace Database\Seeders;

use App\Models\Image;
use Illuminate\Database\Seeder;

class ImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/libro.png";
        $imagen->imageable_id = 1;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/globo.png";
        $imagen->imageable_id = 2;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/melon.png";
        $imagen->imageable_id = 3;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/limon.png";
        $imagen->imageable_id = 4;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/sol.png";
        $imagen->imageable_id = 5;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/nube.png";
        $imagen->imageable_id = 6;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/papa.png";
        $imagen->imageable_id = 7;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/mama.png";
        $imagen->imageable_id = 8;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/pan.png";
        $imagen->imageable_id = 9;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/carne.png";
        $imagen->imageable_id = 10;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/perro.png";
        $imagen->imageable_id = 11;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/mono.png";
        $imagen->imageable_id = 12;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/juguete.png";
        $imagen->imageable_id = 13;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/sandia.png";
        $imagen->imageable_id = 14;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/nopal.png";
        $imagen->imageable_id = 15;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/palmera.png";
        $imagen->imageable_id = 16;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/estrella.png";
        $imagen->imageable_id = 17;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/hermano.png";
        $imagen->imageable_id = 18;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/hermana.png";
        $imagen->imageable_id = 19;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/aguila.png";
        $imagen->imageable_id = 20;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/buho.png";
        $imagen->imageable_id = 21;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/rana.png";
        $imagen->imageable_id = 22;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/cabeza.png";
        $imagen->imageable_id = 23;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/boca.png";
        $imagen->imageable_id = 24;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/almohada.png";
        $imagen->imageable_id = 25;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/cuchara.png";
        $imagen->imageable_id = 26;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/piña.png";
        $imagen->imageable_id = 27;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/platano.png";
        $imagen->imageable_id = 28;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/luna.png";
        $imagen->imageable_id = 29;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/mundo.png";
        $imagen->imageable_id = 30;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/niño.png";
        $imagen->imageable_id = 31;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/abuelo.png";
        $imagen->imageable_id = 32;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/ardilla.png";
        $imagen->imageable_id = 33;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/abeja.png";
        $imagen->imageable_id = 34;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/nariz.png";
        $imagen->imageable_id = 35;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/oreja.png";
        $imagen->imageable_id = 36;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
    }
}
