<?php

namespace Database\Seeders;

use App\Models\Image;
use Illuminate\Database\Seeder;

class ImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/libro.png";
        $imagen->imageable_id = 1;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/globo.png";
        $imagen->imageable_id = 2;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/melon.png";
        $imagen->imageable_id = 3;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/limon.png";
        $imagen->imageable_id = 4;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/sol.png";
        $imagen->imageable_id = 5;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/nube.png";
        $imagen->imageable_id = 6;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/papa.png";
        $imagen->imageable_id = 7;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/mama.png";
        $imagen->imageable_id = 8;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/pan.png";
        $imagen->imageable_id = 9;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/carne.png";
        $imagen->imageable_id = 10;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/perro.png";
        $imagen->imageable_id = 11;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl1/mono.png";
        $imagen->imageable_id = 12;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/juguete.png";
        $imagen->imageable_id = 13;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/sandia.png";
        $imagen->imageable_id = 14;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/nopal.png";
        $imagen->imageable_id = 15;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/palmera.png";
        $imagen->imageable_id = 16;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/estrella.png";
        $imagen->imageable_id = 17;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/hermano.png";
        $imagen->imageable_id = 18;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/hermana.png";
        $imagen->imageable_id = 19;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/aguila.png";
        $imagen->imageable_id = 20;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/buho.png";
        $imagen->imageable_id = 21;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/rana.png";
        $imagen->imageable_id = 22;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/cabeza.png";
        $imagen->imageable_id = 23;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl2/boca.png";
        $imagen->imageable_id = 24;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/almohada.png";
        $imagen->imageable_id = 25;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/cuchara.png";
        $imagen->imageable_id = 26;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/piña.png";
        $imagen->imageable_id = 27;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/platano.png";
        $imagen->imageable_id = 28;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/luna.png";
        $imagen->imageable_id = 29;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/mundo.png";
        $imagen->imageable_id = 30;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/niño.png";
        $imagen->imageable_id = 31;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/abuelo.png";
        $imagen->imageable_id = 32;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/ardilla.png";
        $imagen->imageable_id = 33;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/abeja.png";
        $imagen->imageable_id = 34;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/nariz.png";
        $imagen->imageable_id = 35;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Nahuatl3/oreja.png";
        $imagen->imageable_id = 36;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/escalera.png";
        $imagen->imageable_id = 37;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/trompeta.png";
        $imagen->imageable_id = 38;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/aguacate.png";
        $imagen->imageable_id = 39;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/chile.png";
        $imagen->imageable_id = 40;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/luna.png";
        $imagen->imageable_id = 41;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/estrella.png";
        $imagen->imageable_id = 42;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/papa.png";
        $imagen->imageable_id = 43;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/mama.png";
        $imagen->imageable_id = 44;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/pan.png";
        $imagen->imageable_id = 45;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/araña.png";
        $imagen->imageable_id = 46;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/pescado.png";
        $imagen->imageable_id = 47;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya1/nariz.png";
        $imagen->imageable_id = 48;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/tronco.png";
        $imagen->imageable_id = 49;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/casa.png";
        $imagen->imageable_id = 50;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/papaya.png";
        $imagen->imageable_id = 51;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/cebolla.png";
        $imagen->imageable_id = 52;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/flor.png";
        $imagen->imageable_id = 53;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/mundo.png";
        $imagen->imageable_id = 54;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/abuelo.png";
        $imagen->imageable_id = 55;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/abuela.png";
        $imagen->imageable_id = 56;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/carne.png";
        $imagen->imageable_id = 57;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/ardilla.png";
        $imagen->imageable_id = 58;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/gato.png";
        $imagen->imageable_id = 59;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya2/cabeza.png";
        $imagen->imageable_id = 60;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/libro.png";
        $imagen->imageable_id = 61;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/silla.png";
        $imagen->imageable_id = 62;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/platano.png";
        $imagen->imageable_id = 63;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/guayaba.png";
        $imagen->imageable_id = 64;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/palmera.png";
        $imagen->imageable_id = 65;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/nube.png";
        $imagen->imageable_id = 66;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/niño.png";
        $imagen->imageable_id = 67;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/hermana.png";
        $imagen->imageable_id = 68;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/caballo.png";
        $imagen->imageable_id = 69;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/borrego.png";
        $imagen->imageable_id = 70;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/hombro.png";
        $imagen->imageable_id = 71;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
        $imagen = new Image();
        $imagen->url = "/images/Maya3/pierna.png";
        $imagen->imageable_id = 72;
        $imagen->imageable_type = "App\Models\Activity";
        $imagen->save();
    }
}
