version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    container_name: server
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
  db:
    image: mysql:8.0
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: masehualtlajtoli_schema
      MYSQL_USER: usr_masehual_ow
      MYSQL_PASSWORD: l3ngu45-1ND1G3n45
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db:
