version: '3.3'

services: 
  laravel:
    image: php:7.4-apache
    depends_on: 
      - mysql_db
    volumes: 
      - ./src:/var/www/html/
    ports: 
      - 80:80
  mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: blog_schema
      MYSQL_USER: devuser
      MYSQL_PASSWORD: 1234
    ports: 
      - 3306:3306