name: Docker container

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Compose start
      run: docker-compose up -d
    - name: Docker Compose stop
      run: docker-compose down
