name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copiar archivo .env
      run: cp .env.example .env
    - name: Inlación de dependencias
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Gerando key
      run: php artisan key:generate
    - name: Permisos de directorio
      run: chmod -R 777 storage bootstrap/cache
    - name: Creación de la base de datos
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Executando phpunit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
